my_string = input('Как Вас зовут: ')
print(len("Как Вас зовут "))
print('как вас зовут: ' .upper())
print('КАК ВАС ЗОВУТ: ' .lower())
print('Как Вас зовут: ' .replace(" ", ""))
print(my_string[0])
print(my_string[-1])